_wandb:
    value:
        cli_version: 0.23.0
        e:
            5euxex3ljjdy3fro4r3tj9jvlmpwlnfv:
                args:
                    - --type
                    - zero_shot
                codePath: rank.py
                codePathLocal: rank.py
                email: alvinw2@andrew.cmu.edu
                executable: /opt/anaconda3/envs/ret/bin/python
                git:
                    commit: e0f24833eddfb4e77bad5be80e7d953fd01227f3
                    remote: git@github.com:alvinwang1/Retrieval.git
                host: alvins-air.wifi.local.cmu.edu
                os: macOS-13.5-arm64-arm-64bit
                program: /Users/alvinwang/cs/Retrieval/src/rank.py
                python: CPython 3.10.19
                root: /Users/alvinwang/cs/Retrieval/src
                startedAt: "2025-12-02T14:32:14.008293Z"
                writerId: 5euxex3ljjdy3fro4r3tj9jvlmpwlnfv
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": darwin-arm64
confusion:
    value: "label_score      0.0  1.0  2.0  3.0\ngpt_label_str                      \ncertain value    265  276   79  123\nhigh value       156  113    0    9\nno value         255   49    9   15\npotential value   15   68   29   38"
label_counts:
    value:
        certain value: 743
        high value: 278
        no value: 328
        potential value: 150
label_map:
    value:
        certain value: 2
        high value: 3
        no value: 0
        potential value: 1
num_sentences:
    value: 1499
term:
    value: independent economic value
type:
    value: zero_shot
