_wandb:
    value:
        cli_version: 0.23.0
        e:
            lgpeqjpca0ymbhdqa2g1jdzty2vdyql2:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "10737418240"
                args:
                    - --type
                    - probabilities
                    - --prompt
                    - system_prompts/zero_shot_v2.txt
                    - --model
                    - openai/gpt-oss-120b
                    - --workers
                    - "1"
                    - --log
                    - "true"
                    - --terms
                    - electronic signature,essential step,unreasonably low prices,useful improvement
                codePath: run_multi.py
                codePathLocal: run_multi.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "204816322560"
                email: alvinw2@andrew.cmu.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 1d4640aa455c1309e9bb38bfe559017fd7ccd22f
                    remote: git@github.com:alvinwang1/Retrieval.git
                host: alvins-air.wifi.local.cmu.edu
                memory:
                    total: "8589934592"
                os: macOS-14.8.3-arm64-arm-64bit
                program: /Users/alvinwang/cs/Retrieval/Retrieval/run_multi.py
                python: CPython 3.12.7
                root: /Users/alvinwang/cs/Retrieval/Retrieval
                startedAt: "2026-04-24T15:51:48.373078Z"
                writerId: lgpeqjpca0ymbhdqa2g1jdzty2vdyql2
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
                - 95
            "2":
                - 5
                - 53
                - 95
            "3":
                - 2
                - 16
            "4": 3.12.7
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
confusion:
    value: "gpt_label_str  distribution\nlabel_score                \n0.0                     935\n1.0                    1449\n2.0                    1367\n3.0                     115"
label_counts:
    value:
        distribution: 3866
label_map:
    value:
        certain value: 2
        high value: 3
        no value: 0
        potential value: 1
num_sentences:
    value: 3866
term:
    value: useful improvement
type:
    value: probabilities
