_wandb:
    value:
        cli_version: 0.23.0
        e:
            w3g5gw8r7g6xszult4kdelnucp2unqvw:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                args:
                    - --type
                    - zero_shot
                codePath: rank.py
                codePathLocal: rank.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "200000000000"
                        used: "185980751872"
                email: alvinw2@andrew.cmu.edu
                executable: /opt/anaconda3/envs/ret/bin/python
                git:
                    commit: e0f24833eddfb4e77bad5be80e7d953fd01227f3
                    remote: git@github.com:alvinwang1/Retrieval.git
                host: alvins-air.wifi.local.cmu.edu
                memory:
                    total: "8589934592"
                os: macOS-13.5-arm64-arm-64bit
                program: /Users/alvinwang/cs/Retrieval/src/rank.py
                python: CPython 3.10.19
                root: /Users/alvinwang/cs/Retrieval/src
                startedAt: "2025-12-02T14:14:56.601012Z"
                writerId: w3g5gw8r7g6xszult4kdelnucp2unqvw
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": darwin-arm64
confusion:
    value:
        "0.0":
            certain value: 266
            high value: 201
            no value: 216
            potential value: 18
        "1.0":
            certain value: 267
            high value: 125
            no value: 49
            potential value: 71
        "2.0":
            certain value: 81
            high value: 2
            no value: 4
            potential value: 29
        "3.0":
            certain value: 129
            high value: 1
            no value: 15
            potential value: 41
label_counts:
    value:
        certain value: 743
        high value: 329
        no value: 284
        potential value: 159
label_map:
    value:
        certain value: 2
        high value: 3
        no value: 0
        potential value: 1
num_sentences:
    value: 1515
term:
    value: independent economic value
type:
    value: zero_shot
